trigger:
  branches:
    include:
    - develop
    - master
    - hotfix/*
    - release/*

pr:
  branches:
    include:
    - master
    - release/*

variables:
- group: Terraform
- group: PipelinesCrosscutting
- name: provisionPath
  value: provision
- name: location
  value: 'westeurope'
- name: environment
  value: $(AzureSubscriptionName)
- name: repositoryName
  value: 'StockTracker'

resources:
  containers:
    - container: azurite
      image: "mcr.microsoft.com/azure-storage/azurite"
      ports:
        - 10000:10000 
        - 10001:10001 
        - 10002:10002 

pool:
  vmImage: 'ubuntu-latest'
  
stages:
  - template: /pipelines/ci-cd-validation.yml
    parameters:       
      provisionPath: $(provisionPath)
      location: $(location)
      serviceConnection: $(TerraformBackendServiceConnectionName)
      environmentName: $(environment)
      repositoryName: $(repositoryName)